### ISSUE TITLE
unexpected status code

### ISSUE THREAD

**Issue by khelaram20** [winsnip/BybitCoinsweeper#1]
![MINGW64__c_Users_Pede_Desktop_pyth bot_drft_party-main12_drft-party-bot-master 07-09-2024 10_07_50](https://github.com/user-attachments/assets/e93fcc39-7bb1-4295-8b57-538ce20cf4a3)
previously it was working fine but now getting this error

**Comment by JustPandaEver** [comment]
this, not my code sir
