### ISSUE TITLE
No points in the game

### ISSUE THREAD

**Issue by miliardov** [winsnip/BybitCoinsweeper#4]
![image](https://github.com/user-attachments/assets/8761ef2b-8222-4f22-9ab1-9a4122ce4fc5)

Judging by the photo the code works, it writes successfully in the console, but in the game itself the points remain the same as they were. Either the points are counted incorrectly or h.

**Comment by miliardov** [comment]
![image](https://github.com/user-attachments/assets/3d524741-5917-46c4-b2a4-8ebbbcdc38cc)

I added to the code the output of responses from the server, everything looks correct for the first two requests, so the problem is in the win request, in it the response is empty even if the request is successful or not.

I saw in your code that the "i" variable has the suffix "$2f1" at the end.
Does the server give it automatically when requesting "me" or do you add it?

**Comment by sonnt612** [comment]
I have the same problem

**Comment by miliardov** [comment]
Sec | Points
89 | 322.0253
98 | 315.0253
109 | 298.0243
111 | 296.0243
127 | 285.0231
159 | 285.0215

Playing the game results in these scores. The formula in the code does not work like this.

And from the real game data, I checked with the code what “h” would get and it doesn't match the “h” that was sent in the “win” request in the real game.

**Comment by codenewinsight** [comment]
> Sec | Points 89 | 322.0253 98 | 315.0253 109 | 298.0243 111 | 296.0243 127 | 285.0231 159 | 285.0215
> 
> Playing the game results in these scores. The formula in the code does not work like this.
> 
> And from the real game data, I checked with the code what “h” would get and it doesn't match the “h” that was sent in the “win” request in the real game.

Need some dev can check and find out how to caculate score and Hash. Otherwise, very risky to use code.
I prefer to use Console script is more safe

**Comment by miliardov** [comment]
> > Sec | Points 89 | 322.0253 98 | 315.0253 109 | 298.0243 111 | 296.0243 127 | 285.0231 159 | 285.0215
> > Playing the game results in these scores. The formula in the code does not work like this.
> > And from the real game data, I checked with the code what “h” would get and it doesn't match the “h” that was sent in the “win” request in the real game.
> 
> Need some dev can check and find out how to caculate score and Hash. Otherwise, very risky to use code. I prefer to use Console script is more safe

are you using a console script?
can you tell me if it is publicly available somewhere?

**Comment by JustPandaEver** [comment]
hash is 100% valid for now,but i dont know how to calculate score

**Comment by vanhbakaa** [comment]
> 89

i found out all but they still not work

**Comment by vanhbakaa** [comment]
point is based on game id 
![image](https://github.com/user-attachments/assets/3dc2ab53-af52-4b9a-9b2f-48c5351d0730)

**Comment by JustPandaEver** [comment]
Thanks sir,i Will update my code
